---
- name: Launch EC2 instance
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/custom.yml
    - vars/common.yml
    - vars/ec2.yml
    - vars/build.yml
  roles:
    - { role: launch, instance: '{{ ami_builder }}', launch_group: {} }
