---
- name: stop master instance
  gather_facts: no
  hosts: localhost
  vars_files:
    - vars/custom.yml
    - vars/common.yml
    - vars/ec2.yml
    - vars/launch.yml
  tasks:
    - amazon.aws.ec2_instance:
        state: 'stopped'
        region: '{{ ec2.region }}'
        instance_ids: '{{ hostvars[item].ec2_id }}'
      with_items:
        - '{{ groups[master.group]|default([]) }}'
